### ISSUE TITLE
Bump number + push to RubyGems to get spellcheck/lang working

### ISSUE THREAD

**Issue by wkoszek** [minivan/middleman-spellcheck#13]
Ivan, do you think there's a chance to push the spellcheck fixes to RubyGems?

Not having this functionality in a public Gems repo makes it hard for me to integrate my build with Circle CI.

Let me know if I can help

Wojciech

**Comment by minivan** [comment]
@wkoszek, thanks for pinging me!

:tada: Done: https://rubygems.org/gems/middleman-spellcheck/versions/0.8.0. :tada:

Does this work?

**Comment by wkoszek** [comment]
@minivan Sorry for delay. It worked for me. I can render the website with the newest middleman-spellcheck just fine.

**Comment by minivan** [comment]
Great to hear that, thanks!
